<?php
require_once 'includes/auth_check.php';
require_once 'backend/services/OwnerAccessService.php';
if(!OwnerAccessService::allowed(getDb(),(int)($_SESSION['user_id']??0))){http_response_code(403);include '403.php';exit;}
$currentPage='admin_users';$pageTitle='Owner Operations';require 'includes/layout.php';
?>
<h1>Owner Operations</h1>
<p class="text-muted">Operational incidents and restricted employee credential recovery. Never enter secrets in incident notes.</p>
<div id="ownerAlert" role="alert"></div><div id="ownerSummary" class="mb-3"></div>
<div class="d-flex gap-2 mb-3"><button id="refreshOwner" class="btn btn-outline-primary">Refresh</button><a class="btn btn-outline-secondary" href="admin_tracking_push.php">Tracking attempts</a><a class="btn btn-outline-secondary" href="admin_audit_log.php">Audit history</a><a class="btn btn-outline-secondary" href="admin_users.php">User management</a></div>
<h2 class="h4">Incidents</h2>
<form id="incidentFilters" class="d-flex flex-wrap gap-2 mb-2"><input id="incidentSearch" class="form-control w-auto" aria-label="Search incidents" placeholder="Workflow or error code"><select id="incidentStatus" class="form-select w-auto" aria-label="Incident status"><option value="">All statuses</option><option>New</option><option>Investigating</option><option>User Error</option><option>System Bug</option><option>Resolved</option></select><select id="incidentSeverity" class="form-select w-auto" aria-label="Severity"><option value="">All severities</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><button class="btn btn-secondary">Filter</button></form>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>Error / workflow</th><th>Users</th><th>Occurrences</th><th>First / last seen</th><th>Severity</th><th>Status</th><th></th></tr></thead><tbody id="incidentRows"></tbody></table></div>
<div class="d-flex gap-2 mb-3"><button id="incidentPrev" class="btn btn-sm btn-outline-secondary">Previous</button><span id="incidentPage"></span><button id="incidentNext" class="btn btn-sm btn-outline-secondary">Next</button></div>
<section id="incidentDetail" class="card p-3 mb-3" hidden><h3 class="h5" id="incidentTitle"></h3><pre id="incidentEvents" style="white-space:pre-wrap"></pre><div id="incidentLinks" class="mb-2"></div><label>Classification <select id="incidentEditStatus" class="form-select"><option>New</option><option>Investigating</option><option>User Error</option><option>System Bug</option><option>Resolved</option></select></label><label>Owner notes / resolution <textarea id="incidentNotes" class="form-control" maxlength="2000"></textarea></label><div class="mt-2"><button id="incidentSave" class="btn btn-primary">Save resolution</button> <button id="incidentClose" class="btn btn-secondary">Close</button></div></section>
<h2 class="h4">Employee credential recovery</h2><p>Recovery requires verified owner access, a recent sign-in, your password, an authenticator code, and durable immutable audit delivery. Revealed values clear after 20 seconds or when this page loses focus.</p>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>User</th><th>Role</th><th>Account status</th><th>Last login</th><th>Recovery status</th><th></th></tr></thead><tbody id="credentialRows"></tbody></table></div>
<form id="revealForm" class="card p-3 mb-3" hidden autocomplete="off"><h3 class="h5" id="revealTitle"></h3><label>Your password <input id="ownerReauth" type="password" class="form-control" autocomplete="current-password" required></label><label>Authenticator code <input id="ownerVerificationCode" class="form-control" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><label>Reason <input id="revealReason" class="form-control" maxlength="200" minlength="5" required></label><div class="mt-2"><button id="revealSubmit" class="btn btn-warning">Reveal for 20 seconds</button> <button type="button" id="revealClose" class="btn btn-secondary">Hide / close</button></div><output id="revealedCredential" class="mt-2" aria-live="polite"></output></form>
<h2 class="h4">Recent users and security activity</h2><pre id="ownerActivity" style="white-space:pre-wrap"></pre>
<?php $pageScript='/cargochina/frontend/js/owner_control.js';require 'includes/footer.php'; ?>
