<?php
require_once dirname(__DIR__).'/backend/config/database.php';$pdo=getDb();
function customerCheck($ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
customerCheck($pdo->query('SELECT DATABASE()')->fetchColumn()==='clms_hardening_20260919','Customer fixtures require isolated database');
if(($argv[1]??'')==='--worker'){
    session_start();$req=json_decode($argv[2],true);$_SESSION=['user_id'=>$req['user_id']??1,'user_roles'=>($req['user_id']??1)===1?['SuperAdmin']:[]];$_GET=$req['query']??[];
    if(($req['resource']??'')==='portal-consume'){require_once dirname(__DIR__).'/backend/services/CustomerPortalService.php';echo json_encode(['accepted'=>CustomerPortalService::consume($pdo,$req['body']['token'])!==null]);exit;}
    if(($req['resource']??'')==='portal-render'){$_GET=['token'=>$req['body']['token']];ob_start();require dirname(__DIR__).'/customer_portal.php';$html=ob_get_clean();echo json_encode(['cumulative_cbm'=>str_contains($html,'0.2500'),'cumulative_weight'=>str_contains($html,'25.00 kg')]);exit;}
    $handler=require dirname(__DIR__).'/backend/api/handlers/'.($req['resource']??'customers').'.php';try{$handler($req['method'],$req['id']??null,$req['action']??null,$req['body']??[]);}catch(Throwable $e){jsonError($e->getMessage(),500);}exit;
}
function customerStart(array $req):array{$pipes=[];$p=proc_open([PHP_BINARY,__FILE__,'--worker',json_encode($req)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);return [$p,$pipes];}
function customerFinish(array $worker):array{[$p,$pipes]=$worker;$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);customerCheck($exit===0&&$err==='','Customer worker failed: '.$err.' '.$out);$result=json_decode($out,true);customerCheck(is_array($result),'Invalid customer JSON: '.$out);return $result;}
function customerCall(string $method,$id,array $body=[],?string $action=null):array{return customerFinish(customerStart(['method'=>$method,'id'=>$id===null?null:(string)$id,'body'=>$body,'action'=>$action]));}
$country=(int)$pdo->query("SELECT id FROM countries WHERE code='LB'")->fetchColumn();
$base=['name'=>'Cedar Coast Homeware','default_shipping_code'=>'CEDAR-COAST-'.bin2hex(random_bytes(3)),'email'=>'purchasing@example.invalid','phone'=>'+961 1 555 014','address'=>'Mar Mikhael, Beirut','contacts'=>[['name'=>'Rana Haddad','role'=>'Purchasing']],'country_shipping'=>[['country_id'=>$country,'shipping_code'=>'CEDAR-BEY-'.bin2hex(random_bytes(3))]],'por'=>['Beirut retail replenishment'],'idempotency_key'=>'customer-qa-'.bin2hex(random_bytes(8))];
$a=customerStart(['method'=>'POST','body'=>$base]);$b=customerStart(['method'=>'POST','body'=>$base]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Customer creation retry diverged: '.json_encode([$ra,$rb]));$id=(int)$ra['data']['id'];$revision=$ra['data']['revision'];
$different=$base;$different['name']='Different customer';customerCheck(!empty(customerCall('POST',null,$different)['error']),'Changed customer payload reused request');
foreach(['email','priority','note','country','country-duplicate','array','long'] as $case){$bad=$base;$bad['idempotency_key']='customer-invalid-'.bin2hex(random_bytes(6));if($case==='email')$bad['email']='broken-email';if($case==='priority')$bad['priority_level']='urgent';if($case==='note')$bad['priority_level']='high';if($case==='country')$bad['country_shipping'][0]['country_id']='1bad';if($case==='country-duplicate')$bad['country_shipping'][]=$bad['country_shipping'][0];if($case==='array')$bad['name']=[];if($case==='long')$bad['code']=str_repeat('C',51);customerCheck(!empty(customerCall('POST',null,$bad)['error']),'Customer accepted '.$case);}
echo "PASS: customer creation concurrency/payload identity and shared validation\n";
$edit=['revision'=>$revision,'name'=>'Cedar Coast Homeware — Beirut'];$a=customerStart(['method'=>'PUT','id'=>(string)$id,'body'=>$edit]);$edit['name']='Cedar Coast Homeware — Wholesale';$b=customerStart(['method'=>'PUT','id'=>(string)$id,'body'=>$edit]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(count(array_filter([$ra,$rb],fn($r)=>!empty($r['error'])))===1,'Concurrent buyer edits overwrote');
$saved=customerCall('GET',$id)['data'];customerCheck($saved['email']===$base['email']&&$saved['contacts']===$base['contacts']&&count($saved['country_shipping'])===1&&$saved['por']===$base['por'],'Partial update erased omitted metadata');
customerCheck(!empty(customerCall('PUT',$id,['name'=>'Unversioned edit'])['error']),'Missing customer revision accepted');
echo "PASS: versioned edits preserve omitted metadata and reject competing operators\n";
$prefix='IMPORT-'.bin2hex(random_bytes(4));$csv="code,name,email,address\n$prefix-A,Cedar Dining,purchasing@example.invalid,\"Beirut, Lebanon\"\n$prefix-B,Harbour Homeware,orders@example.invalid,\"Tripoli\nLebanon\"";$import=['csv'=>$csv,'idempotency_key'=>'customer-import-'.bin2hex(random_bytes(7))];
$a=customerStart(['method'=>'POST','id'=>'import','body'=>$import]);$b=customerStart(['method'=>'POST','id'=>'import','body'=>$import]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(($ra['data']['created']??0)===2&&($rb['data']['created']??0)===2,'CSV concurrent import failed');$s=$pdo->prepare('SELECT COUNT(*) FROM customers WHERE code IN (?,?)');$s->execute([$prefix.'-A',$prefix.'-B']);customerCheck((int)$s->fetchColumn()===2,'CSV import duplicated');
$invalidPrefix='ROLLBACK-'.bin2hex(random_bytes(4));$invalid=['csv'=>"code,name,email\n$invalidPrefix-A,Cedar Dining,valid@example.invalid\n$invalidPrefix-B,Harbour Homeware,invalid",'idempotency_key'=>'customer-import-bad-'.bin2hex(random_bytes(6))];$failure=customerCall('POST','import',$invalid);$s=$pdo->prepare('SELECT COUNT(*) FROM customers WHERE code LIKE ?');$s->execute([$invalidPrefix.'%']);customerCheck(!empty($failure['error'])&&!(int)$s->fetchColumn(),'Invalid import left partial buyers');
echo "PASS: quoted/multiline CSV, concurrent replay and atomic invalid batch rollback\n";
$trigger=false;try{$pdo->exec("CREATE TRIGGER qa_customer_update_rollback BEFORE INSERT ON audit_log FOR EACH ROW BEGIN IF NEW.entity_type='customer' AND NEW.action='update' AND NEW.entity_id=$id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected customer audit failure'; END IF; END");$trigger=true;$failed=customerCall('PUT',$id,['revision'=>$saved['revision'],'name'=>'Must roll back']);$after=customerCall('GET',$id)['data'];customerCheck(!empty($failed['error'])&&$after['revision']===$saved['revision'],'Customer audit failure persisted edits');}finally{if($trigger)$pdo->exec('DROP TRIGGER qa_customer_update_rollback');}
$pdo->prepare("INSERT INTO orders(customer_id,status,created_by) VALUES (?,'Draft',1)")->execute([$id]);customerCheck(!empty(customerCall('DELETE',$id,['revision'=>$saved['revision']])['error']),'Customer with cargo history deleted');
$pdo->prepare("INSERT INTO users(email,password_hash,full_name,is_active) VALUES (?,'unusable','Buyer access QA',1)")->execute(['buyer-qa-'.bin2hex(random_bytes(5)).'@example.invalid']);$reader=(int)$pdo->lastInsertId();foreach(['GET','POST','PUT','DELETE'] as $method)customerCheck(!empty(customerFinish(customerStart(['method'=>$method,'id'=>$method==='POST'?null:(string)$id,'user_id'=>$reader]))['error']),'Roleless customer access accepted');
echo "PASS: audit rollback, linked customer deletion guard and direct access authorization\n";
$orderId=(int)$pdo->query('SELECT MAX(id) FROM orders WHERE customer_id='.$id)->fetchColumn();
$payment=['amount'=>'125.2500','currency'=>'USD','payment_method'=>'Bank Transfer','reference_no'=>'BEY-REPLENISHMENT','order_id'=>$orderId,'idempotency_key'=>'deposit-qa-'.bin2hex(random_bytes(8))];
$a=customerStart(['method'=>'POST','id'=>(string)$id,'action'=>'deposits','body'=>$payment]);$b=customerStart(['method'=>'POST','id'=>(string)$id,'action'=>'deposits','body'=>$payment]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Concurrent customer deposits diverged: '.json_encode([$ra,$rb]));
$other=(int)$pdo->query('SELECT id FROM customers WHERE id<>'.$id.' LIMIT 1')->fetchColumn();$wrong=$payment;$wrong['idempotency_key']='wrong-buyer-'.bin2hex(random_bytes(6));customerCheck(!empty(customerCall('POST',$other,$wrong,'deposits')['error']),'Cross-buyer order deposit accepted');
foreach([['amount'=>'100000000'],['amount'=>[]],['currency'=>'EUR'],['order_id'=>'1bad'],['payment_method'=>[]]] as $invalid){$bad=array_merge($payment,$invalid,['idempotency_key'=>'deposit-bad-'.bin2hex(random_bytes(6))]);customerCheck(!empty(customerCall('POST',$id,$bad,'deposits')['error']),'Invalid deposit accepted');}
$ledger=['party_type'=>'customer','party_id'=>$id,'transaction_type'=>'payment_received','direction'=>'reduce_balance','amount'=>'50','currency'=>'USD','transaction_date'=>'2026-09-19','payment_method'=>null,'order_id'=>$orderId,'idempotency_key'=>'ledger-qa-'.bin2hex(random_bytes(8))];
$a=customerStart(['resource'=>'balances','method'=>'POST','id'=>'transactions','body'=>$ledger]);$b=customerStart(['resource'=>'balances','method'=>'POST','id'=>'transactions','body'=>$ledger]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Concurrent balance deposits diverged: '.json_encode([$ra,$rb]));
$s=$pdo->prepare('SELECT COUNT(*),SUM(amount) FROM customer_deposits WHERE customer_id=?');$s->execute([$id]);$totals=$s->fetch(PDO::FETCH_NUM);customerCheck((int)$totals[0]===2&&(float)$totals[1]===175.25,'Deposit totals double counted');
$history=customerFinish(customerStart(['resource'=>'balances','method'=>'GET','id'=>'transactions','query'=>['party_type'=>'customer','party_id'=>$id]]));customerCheck(count($history['data']??[])===2,'Unified history duplicated linked deposit');
$bad=$ledger;$bad['idempotency_key']='direction-bad-'.bin2hex(random_bytes(5));$bad['direction']='increase_balance';customerCheck(!empty(customerFinish(customerStart(['resource'=>'balances','method'=>'POST','id'=>'transactions','body'=>$bad]))['error']),'Payment increased balance');
$trigger=false;try{$pdo->exec("CREATE TRIGGER qa_customer_deposit_rollback BEFORE INSERT ON audit_log FOR EACH ROW BEGIN IF NEW.entity_type IN ('customer_deposit','balance_transaction') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected deposit audit failure'; END IF; END");$trigger=true;
    $bad=$payment;$bad['idempotency_key']='deposit-rollback-'.bin2hex(random_bytes(5));customerCheck(!empty(customerCall('POST',$id,$bad,'deposits')['error']),'Deposit audit failure ignored');
    $bad=$ledger;$bad['idempotency_key']='ledger-rollback-'.bin2hex(random_bytes(5));customerCheck(!empty(customerFinish(customerStart(['resource'=>'balances','method'=>'POST','id'=>'transactions','body'=>$bad]))['error']),'Ledger audit failure ignored');
    $s->execute([$id]);customerCheck($s->fetch(PDO::FETCH_NUM)===$totals,'Deposit rollback leaked financial rows');
}finally{if($trigger)$pdo->exec('DROP TRIGGER qa_customer_deposit_rollback');}
foreach(['customers','balances'] as $resource)customerCheck(!empty(customerFinish(customerStart(['resource'=>$resource,'method'=>'POST','id'=>$resource==='customers'?(string)$id:'transactions','action'=>$resource==='customers'?'deposits':null,'body'=>$resource==='customers'?$payment:$ledger,'user_id'=>$reader]))['error']),'Roleless deposit accepted');
$balance=customerCall('GET',$id,[],'balance');customerCheck((float)($balance['data']['USD']??0)===175.25,'Customer deposits summary mismatch');
echo "PASS: deposit concurrency, buyer ownership, shared validation, currency totals, unified history and rollback\n";
foreach(["name\n\"Unclosed", "name\n\"Closed\"junk", "name,name\nA,B", "name\nA,B"] as $csv)customerCheck(!empty(customerCall('POST','import',['csv'=>$csv,'idempotency_key'=>'csv-malformed-'.bin2hex(random_bytes(5))])['error']),'Malformed CSV accepted');
$portal=['customer_id'=>$id,'hours'=>24,'idempotency_key'=>'portal-qa-'.bin2hex(random_bytes(8))];
$link=customerFinish(customerStart(['resource'=>'customer-portal-tokens','method'=>'POST','body'=>$portal]));customerCheck(!empty($link['data']['token']),'Portal link generation failed');
$again=customerFinish(customerStart(['resource'=>'customer-portal-tokens','method'=>'POST','body'=>$portal]));customerCheck(!empty($again['error']),'Portal creation retry generated a second token');
$a=customerStart(['resource'=>'portal-consume','body'=>['token'=>$link['data']['token']]]);$b=customerStart(['resource'=>'portal-consume','body'=>['token'=>$link['data']['token']]]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck((int)$ra['accepted']+(int)$rb['accepted']===1,'One-time portal token consumed concurrently');
$message=['customer_id'=>$id,'order_id'=>$orderId,'body'=>'Packaging inspection complete. Awaiting scheduled collection.','idempotency_key'=>'message-qa-'.bin2hex(random_bytes(7))];
$a=customerStart(['resource'=>'internal-messages','method'=>'POST','body'=>$message]);$b=customerStart(['resource'=>'internal-messages','method'=>'POST','body'=>$message]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Internal message replay duplicated');
$bad=$message;$bad['customer_id']=$other;$bad['idempotency_key']='message-owner-'.bin2hex(random_bytes(5));customerCheck(!empty(customerFinish(customerStart(['resource'=>'internal-messages','method'=>'POST','body'=>$bad]))['error']),'Cross-buyer message order accepted');
$upload='uploads/qa-buyer-'.bin2hex(random_bytes(7)).'.png';$absolute=dirname(__DIR__).'/backend/'.$upload;file_put_contents($absolute,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jXu0AAAAASUVORK5CYII='));
try{$attachment=['entity_type'=>'customer','entity_id'=>$id,'file_path'=>$upload,'file_type'=>'png'];$a=customerStart(['resource'=>'design-attachments','method'=>'POST','body'=>$attachment]);$b=customerStart(['resource'=>'design-attachments','method'=>'POST','body'=>$attachment]);$ra=customerFinish($a);$rb=customerFinish($b);customerCheck(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Attachment retry duplicated: '.json_encode([$ra,$rb]));
    $removed=customerFinish(customerStart(['resource'=>'design-attachments','method'=>'DELETE','id'=>(string)$ra['data']['id']]));customerCheck(!empty($removed['data']['deleted']),'Attachment deletion failed');
}finally{unlink($absolute);}
foreach(['customer-portal-tokens','internal-messages','design-attachments'] as $resource)customerCheck(!empty(customerFinish(customerStart(['resource'=>$resource,'method'=>'POST','user_id'=>$reader,'body'=>$resource==='customer-portal-tokens'?$portal:($resource==='internal-messages'?$message:$attachment)]))['error']),'Roleless related customer action accepted');
echo "PASS: malformed CSV rejection, one-time portal concurrency, message ownership/replay and attachment deduplication\n";
$pdo->prepare("INSERT INTO orders(customer_id,status,created_by) VALUES (?,'ReadyForConsolidation',1)")->execute([$id]);$cargoOrder=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO order_items(order_id,quantity,cartons,qty_per_carton,declared_cbm,declared_weight,description_en,shipping_code,item_no) VALUES (?,10,2,5,.8,60,'Cotton kitchen towels','COAST-BEY','COAST-BEY-1-1')")->execute([$cargoOrder]);$cargoItem=(int)$pdo->lastInsertId();
for($i=0;$i<2;$i++){$pdo->prepare("INSERT INTO warehouse_receipts(order_id,actual_cartons,actual_cbm,actual_weight,receipt_condition,received_by) VALUES (?,1,.125,12.5,'good',1)")->execute([$cargoOrder]);$receipt=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO warehouse_receipt_items(receipt_id,order_item_id,actual_cartons,actual_quantity,actual_cbm,actual_weight,receipt_condition) VALUES (?,?,1,5,.125,12.5,'good')")->execute([$receipt,$cargoItem]);}
$portal['idempotency_key']='portal-cumulative-'.bin2hex(random_bytes(6));$link=customerFinish(customerStart(['resource'=>'customer-portal-tokens','method'=>'POST','body'=>$portal]));$view=customerFinish(customerStart(['resource'=>'portal-render','body'=>['token'=>$link['data']['token']]]));customerCheck($view['cumulative_cbm']&&$view['cumulative_weight'],'Customer portal does not use cumulative physical totals');
$current=customerCall('GET',$id)['data'];$renamed=customerCall('PUT',$id,['revision'=>$current['revision'],'default_shipping_code'=>$base['default_shipping_code'].'-NEW']);customerCheck(empty($renamed['error']),'Buyer shipping-code update failed');$item=$pdo->query('SELECT item_no,shipping_code FROM order_items WHERE id='.$cargoItem)->fetch(PDO::FETCH_ASSOC);customerCheck($item===['item_no'=>'COAST-BEY-1-1','shipping_code'=>'COAST-BEY'],'Buyer edit rewrote historic cargo identifiers');
echo "PASS: customer portal cumulative physical totals and immutable existing cargo identity\n";
if(($argv[1]??'')==='--ui')echo json_encode(['customer'=>$id,'shipping_code'=>$base['default_shipping_code']]);
