<?php
require_once dirname(__DIR__).'/backend/config/database.php';$pdo=getDb();
function importCheck($ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
importCheck($pdo->query('SELECT DATABASE()')->fetchColumn()==='clms_hardening_20260919','Import fixtures require isolated database');
if(($argv[1]??'')==='--worker'){
    session_start();$r=json_decode($argv[2],true);$_SESSION=['user_id'=>$r['user']??1,'user_roles'=>($r['user']??1)===1?['SuperAdmin']:[]];$_GET=$r['query']??[];
    if(isset($r['file']))$_FILES=['file'=>['name'=>$r['filename']??'cargo.csv','tmp_name'=>$r['file'],'size'=>filesize($r['file']),'error'=>UPLOAD_ERR_OK]];
    $handler=require dirname(__DIR__).'/backend/api/handlers/'.$r['resource'].'.php';try{$handler($r['method']??'POST',array_key_exists('id',$r)?$r['id']:'import',$r['action']??null,$r['body']??[]);}catch(Throwable $e){jsonError($e->getMessage(),500);}exit;
}
function importStart(array $r):array{$pipes=[];$p=proc_open([PHP_BINARY,__FILE__,'--worker',json_encode($r)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);return [$p,$pipes];}
function importFinish(array $w):array{[$p,$pipes]=$w;$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);importCheck($exit===0&&$err==='','Import worker error: '.$err.' '.$out);$r=json_decode($out,true);importCheck(is_array($r),'Invalid import output: '.substr($out,0,400));return $r;}
function importCall(array $r):array{return importFinish(importStart($r));}
function importBody(string $csv):array{return ['csv'=>$csv,'idempotency_key'=>'import-qa-'.bin2hex(random_bytes(10))];}
$prefix='SUP-'.bin2hex(random_bytes(5));$phone=(string)random_int(100000000,999999999);$csv="code,name,phone,address\n$prefix-A,Guangzhou Coast Ceramics $prefix,+86 $phone 11,\"Panyu District\nGuangzhou\"\n$prefix-B,Foshan Bamboo Works $prefix,+86 $phone 22,\"Nanhai, Foshan\"";$body=importBody($csv);
$a=importStart(['resource'=>'suppliers','body'=>$body]);$b=importStart(['resource'=>'suppliers','body'=>$body]);$ra=importFinish($a);$rb=importFinish($b);importCheck(($ra['data']['created']??0)===2&&($rb['data']['created']??0)===2,'Supplier import retry failed: '.json_encode([$ra,$rb]));
$s=$pdo->prepare('SELECT COUNT(*) FROM suppliers WHERE code IN (?,?)');$s->execute([$prefix.'-A',$prefix.'-B']);importCheck((int)$s->fetchColumn()===2,'Concurrent suppliers duplicated');
$badPrefix='ROLL-'.bin2hex(random_bytes(5));$bad=importCall(['resource'=>'suppliers','body'=>importBody("code,name,phone\n$badPrefix-A,Yiwu Linen Works,+86 579 5555 0101\n$badPrefix-B,Ningbo Houseware,not-a-phone")]);$s=$pdo->prepare('SELECT COUNT(*) FROM suppliers WHERE code LIKE ?');$s->execute([$badPrefix.'%']);importCheck(!empty($bad['error'])&&!(int)$s->fetchColumn(),'Supplier invalid batch partially committed');
$duplicate=importCall(['resource'=>'suppliers','body'=>importBody($csv)]);importCheck(($duplicate['data']['skipped']??0)===2,'Existing supplier codes not skipped');
echo "PASS: strict multiline supplier CSV, concurrent replay, duplicate codes and atomic rollback\n";
$type=$pdo->query("SELECT code FROM item_types WHERE code<>'unclassified' ORDER BY code LIMIT 1")->fetchColumn();$label='Bamboo serving trays '.bin2hex(random_bytes(5));
$productCsv="description_en,cbm,weight,length_cm,width_cm,height_cm,pieces_per_carton,unit_price,supplier_code,item_type_code,item_type_confirmed\n$label,0.12,18,60,40,50,24,4.25,$prefix-A,$type,1";$body=importBody($productCsv);
$a=importStart(['resource'=>'products','body'=>$body]);$b=importStart(['resource'=>'products','body'=>$body]);$ra=importFinish($a);$rb=importFinish($b);importCheck(($ra['data']['created']??0)===1&&($rb['data']['created']??0)===1,'Product concurrent import failed: '.json_encode([$ra,$rb]));
$s=$pdo->prepare("SELECT p.*,ic.item_type_code,ic.is_confirmed FROM products p JOIN item_classifications ic ON ic.entity_type='product' AND ic.entity_id=p.id WHERE p.description_en=?");$s->execute([$label]);$products=$s->fetchAll(PDO::FETCH_ASSOC);importCheck(count($products)===1&&(float)$products[0]['cbm']===.12&&(int)$products[0]['pieces_per_carton']===24&&(int)$products[0]['is_confirmed']===1,'Product totals/classification mismatch');$productId=(int)$products[0]['id'];
foreach(['negative','nan','fraction','unknown-supplier','unconfirmed','missing-type'] as $case){$row=['description_en'=>'Cotton linens '.bin2hex(random_bytes(4)),'cbm'=>.12,'weight'=>12,'pieces_per_carton'=>24,'supplier_code'=>$prefix.'-A','item_type_code'=>$type,'item_type_confirmed'=>1];if($case==='negative')$row['weight']=-1;if($case==='nan')$row['cbm']='12oops';if($case==='fraction')$row['pieces_per_carton']=1.5;if($case==='unknown-supplier')$row['supplier_code']='NO-SUCH-SUPPLIER';if($case==='unconfirmed')$row['item_type_confirmed']=0;if($case==='missing-type')unset($row['item_type_code']);$bad=importCall(['resource'=>'products','body'=>importBody(implode(',',array_keys($row))."\n".implode(',',array_values($row)))]);importCheck(!empty($bad['error']),'Invalid product import accepted: '.$case);}
$manual=importCall(['resource'=>'products','id'=>null,'body'=>['description_en'=>'Invalid manual dimensions','cbm'=>1,'weight'=>-2,'item_type_code'=>$type,'item_type_confirmed'=>true]]);importCheck(!empty($manual['error']),'Manual product bypassed import numeric rule');
echo "PASS: product retry, dimensional CBM, required classification and shared manual/import validation\n";
$trigger=false;try{$pdo->exec("CREATE TRIGGER qa_import_rollback BEFORE INSERT ON audit_log FOR EACH ROW BEGIN IF NEW.entity_type='product_import' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected import audit failure'; END IF; END");$trigger=true;$rollbackLabel='Woven storage baskets '.bin2hex(random_bytes(5));$failed=importCall(['resource'=>'products','body'=>importBody("description_en,cbm,weight,item_type_code,item_type_confirmed\n$rollbackLabel,.2,10,$type,1")]);$s=$pdo->prepare('SELECT COUNT(*) FROM products WHERE description_en=?');$s->execute([$rollbackLabel]);importCheck(!empty($failed['error'])&&!(int)$s->fetchColumn(),'Import audit failure leaked product');}finally{if($trigger)$pdo->exec('DROP TRIGGER qa_import_rollback');}
$pdo->prepare("INSERT INTO users(email,password_hash,full_name,is_active) VALUES (?,'unusable','Import access QA',1)")->execute(['import-qa-'.bin2hex(random_bytes(5)).'@example.invalid']);$reader=(int)$pdo->lastInsertId();foreach(['products','suppliers','customers','draft-orders','receiving','hs-code-catalog'] as $resource){$bad=importCall(['resource'=>$resource,'action'=>$resource==='receiving'?'preview':null,'user'=>$reader,'body'=>$body]);importCheck(!empty($bad['error']),'Roleless import allowed: '.$resource);}
$temp=tempnam(sys_get_temp_dir(),'qa_import_');try{
    foreach(['12oops','1,2','NaN','=10+2'] as $number){file_put_contents($temp,"English Item Name,Cartons,Pieces/Carton,CBM/Unit,Weight/Unit\nBamboo baskets,\"$number\",6,.12,8");$bad=importCall(['resource'=>'draft-orders','file'=>$temp]);importCheck(!empty($bad['error']),'Draft import silently converted malformed number: '.$number);}
    file_put_contents($temp,"English Item Name,Cartons\n\"Unclosed basket,2");$bad=importCall(['resource'=>'draft-orders','file'=>$temp]);importCheck(!empty($bad['error']),'Draft import accepted malformed quotes');
}finally{unlink($temp);}
echo "PASS: audit rollback, direct import permissions and malformed draft CSV/number rejection\n";
$supplier=(int)$products[0]['supplier_id'];$customer=(int)$pdo->query('SELECT id FROM customers ORDER BY id LIMIT 1')->fetchColumn();
$item=['product_id'=>$productId,'supplier_id'=>$supplier,'description_cn'=>str_repeat('竹制托盘',120),'description_en'=>str_repeat('Protective packaging. ',30),'cartons'=>2,'qty_per_carton'=>6,'quantity'=>12,'unit'=>'pieces','dimensions_scope'=>'carton','declared_cbm'=>.24,'declared_weight'=>36,'unit_price'=>4.25,'sell_price'=>6.5,'total_amount'=>78,'item_no'=>'OLD-BUYER-1-1','shipping_code'=>'OLD-BUYER'];
$body=['name'=>'Autumn bamboo serving collection','items'=>[$item],'idempotency_key'=>'template-qa-'.bin2hex(random_bytes(8))];
$a=importStart(['resource'=>'order-templates','id'=>null,'body'=>$body]);$b=importStart(['resource'=>'order-templates','id'=>null,'body'=>$body]);$ra=importFinish($a);$rb=importFinish($b);importCheck(!empty($ra['data']['id'])&&$ra['data']['id']===$rb['data']['id'],'Template replay failed: '.json_encode([$ra,$rb]));$templateId=(int)$ra['data']['id'];
$saved=importCall(['resource'=>'order-templates','method'=>'GET','id'=>(string)$templateId]);$ti=$saved['data']['items'][0]??[];importCheck(($ti['dimensions_scope']??'')==='carton'&&(float)$ti['sell_price']===6.5&&$ti['description_cn']===$item['description_cn']&&$ti['item_no']===null&&$ti['shipping_code']===null,'Template lost measurements, descriptions, pricing or retained buyer numbering');
$bad=$body;$bad['items'][0]['dimensions_scope']='pallet';$bad['idempotency_key'].='bad';importCheck(!empty(importCall(['resource'=>'order-templates','id'=>null,'body'=>$bad])['error']),'Invalid template measurement scope accepted');
importCheck(empty($saved['data']['requires_measurement_review']),'Verified template incorrectly blocked');
$pdo->prepare('UPDATE order_template_items SET dimensions_scope=NULL WHERE template_id=?')->execute([$templateId]);
$legacy=importCall(['resource'=>'order-templates','method'=>'GET','id'=>(string)$templateId]);
importCheck($legacy['data']['requires_measurement_review']===true && $legacy['data']['items'][0]['dimensions_scope']===null,'Unknown historical template basis was invented');
$pdo->prepare("UPDATE order_template_items SET dimensions_scope='carton' WHERE template_id=?")->execute([$templateId]);
unset($item['item_no'],$item['shipping_code']);$item['description_cn']='竹制托盘';$order=importCall(['resource'=>'orders','id'=>null,'body'=>['customer_id'=>$customer,'supplier_id'=>$supplier,'items'=>[$item],'currency'=>'USD','idempotency_key'=>'scope-qa-'.bin2hex(random_bytes(8))]]);importCheck(!empty($order['data']['id']),'Scope order failed: '.json_encode($order));$orderId=(int)$order['data']['id'];
$pdo->prepare("UPDATE products SET dimensions_scope='piece' WHERE id=?")->execute([$productId]);$order=importCall(['resource'=>'orders','method'=>'GET','id'=>(string)$orderId]);importCheck(($order['data']['items'][0]['dimensions_scope']??'')==='carton'&&(float)$order['data']['items'][0]['declared_cbm']===.24,'Historical order measurement basis followed mutable product');
echo "PASS: concurrent templates, complete bilingual text, fresh numbering and immutable order measurement basis\n";
$catalogPath=dirname(__DIR__).'/hs codes/qa_catalog_'.bin2hex(random_bytes(8)).'.csv';$catalogSource=basename($catalogPath);$key='catalog-qa-'.bin2hex(random_bytes(8));
try{
    $catalogCsv="hs_code,name,tariff_rate,vat\n0101.21,Live purebred horses,5 %,11 %\n0101.29,Other live horses,5 %,11 %";file_put_contents($catalogPath,$catalogCsv);
    $r=['resource'=>'hs-code-catalog','body'=>['source'=>$catalogSource,'idempotency_key'=>$key]];$a=importStart($r);$b=importStart($r);$ra=importFinish($a);$rb=importFinish($b);importCheck(($ra['data']['imported']??0)===2&&($rb['data']['imported']??0)===2,'Catalog retry failed: '.json_encode([$ra,$rb]));
    $pdo->exec("UPDATE hs_code_tariff_catalog SET name_en='Purebred horses' WHERE hs_code='0101.21'");$r['body']['idempotency_key'].='next';$saved=importCall($r);importCheck(empty($saved['error'])&&$pdo->query("SELECT name_en FROM hs_code_tariff_catalog WHERE hs_code='0101.21'")->fetchColumn()==='Purebred horses','Catalog translation not preserved');
    $snapshot=$pdo->query('SELECT * FROM hs_code_tariff_catalog ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
    foreach(["hs_code,name\n", "hs_code,name\n0101.21,Horses\n010121,Duplicate", "hs_code,name\n0101.21,\"Unclosed", "hs_code,name\n0101.21," ] as $csv){file_put_contents($catalogPath,$csv);$r['body']['idempotency_key']='catalog-invalid-'.bin2hex(random_bytes(8));$bad=importCall($r);importCheck(!empty($bad['error'])&&$pdo->query('SELECT * FROM hs_code_tariff_catalog ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$snapshot,'Invalid catalog erased previous records');}
    file_put_contents($catalogPath,$catalogCsv);$pdo->exec("CREATE TRIGGER qa_catalog_audit BEFORE INSERT ON audit_log FOR EACH ROW BEGIN IF NEW.entity_type='hs_catalog_import' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Catalog audit failure'; END IF; END");
    try{$r['body']['idempotency_key']='catalog-failure-'.bin2hex(random_bytes(8));$bad=importCall($r);importCheck(!empty($bad['error'])&&$pdo->query('SELECT * FROM hs_code_tariff_catalog ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$snapshot,'Catalog failure did not restore prior state');}finally{$pdo->exec('DROP TRIGGER qa_catalog_audit');}
}finally{unlink($catalogPath);}
echo "PASS: catalog concurrent replay, translation preservation, malformed/duplicate/empty input and replacement rollback\n";
require_once dirname(__DIR__).'/vendor/autoload.php';require_once dirname(__DIR__).'/backend/services/WorkbookImportGuard.php';
$xlsx=tempnam(sys_get_temp_dir(),'qa_book_');try{
    $book=new \PhpOffice\PhpSpreadsheet\Spreadsheet();$sheet=$book->getActiveSheet();$sheet->fromArray([['English Item Name','Cartons','Pieces/Carton','CBM/Unit','Weight/Unit'],['Bamboo baskets',2,6,.12,8]]);$sheet->getCell('B2')->setValue('=1+1')->setCalculatedValue(2);$writer=new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($book);$writer->setPreCalculateFormulas(false);$writer->save($xlsx);$book->disconnectWorksheets();
    $result=importCall(['resource'=>'draft-orders','file'=>$xlsx,'filename'=>'autumn-cargo.xlsx']);importCheck(empty($result['error']),'Saved formula result not imported: '.json_encode($result));
    $zip=new ZipArchive();$zip->open($xlsx);$xml=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->addFromString('xl/worksheets/sheet1.xml',preg_replace('/(<c[^>]*r="B2"[^>]*>.*?<f>.*?<\/f>)<v>.*?<\/v>/s','$1',$xml));$zip->close();$bad=importCall(['resource'=>'draft-orders','file'=>$xlsx,'filename'=>'uncached.xlsx']);importCheck(!empty($bad['error']),'Uncached formula accepted');
    $zip=new ZipArchive();$zip->open($xlsx);$zip->addFromString('xl/_rels/external.rels','<Relationships><Relationship TargetMode="External" Target="http://example.invalid"/></Relationships>');$zip->close();$bad=importCall(['resource'=>'draft-orders','file'=>$xlsx,'filename'=>'external.xlsx']);importCheck(!empty($bad['error']),'External workbook link accepted');
}finally{unlink($xlsx);}
echo "PASS: XLSX cached values only and external links rejected\n";
if(($argv[1]??'')==='--ui')echo json_encode(['supplier_code'=>$prefix.'-A','product'=>$productId,'item_type'=>$type]);
