<?php
require_once dirname(__DIR__).'/backend/config/database.php';require_once dirname(__DIR__).'/backend/services/UploadAccessService.php';$pdo=getDb();
if (getenv('CLMS_TEST_LEGACY_JSON')==='1') { require_once __DIR__.'/support/legacy_no_json_pdo.php';$pdo=new LegacyNoJsonPDO($pdo); }
function mediaCheck($ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
mediaCheck($pdo->query('SELECT DATABASE()')->fetchColumn()==='clms_hardening_20260919','Media tests require isolated database');
if(($argv[1]??'')==='--worker'){$input=json_decode($argv[2],true);if(session_status()===PHP_SESSION_NONE)session_start();$_SESSION=empty($input['user'])?[]:['user_id'=>$input['user'],'user_roles'=>(int)$input['user']===1?['SuperAdmin']:[]];UploadAccessService::authorize($pdo,$input['path'],$input['token']??null);jsonResponse(['allowed'=>true]);}
function mediaCall(array $input):array{$pipes=[];$p=proc_open([PHP_BINARY,__FILE__,'--worker',json_encode($input)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);mediaCheck($exit===0&&$err==='','Media worker failed: '.$err);return json_decode($out,true)??[];}
$customer=(int)$pdo->query('SELECT id FROM customers LIMIT 1')->fetchColumn();$token=bin2hex(random_bytes(32));$path='uploads/qa-media-'.bin2hex(random_bytes(5)).'.png';
$pdo->prepare("INSERT INTO orders(customer_id,status,confirmation_token,created_by) VALUES (?,'Confirmed',?,1)")->execute([$customer,$token]);$order=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO warehouse_receipts(order_id,actual_cartons,actual_cbm,actual_weight,receipt_condition,received_by) VALUES (?,1,.1,10,'good',1)")->execute([$order]);$receipt=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO warehouse_receipt_photos(receipt_id,file_path) VALUES (?,?)')->execute([$receipt,$path]);
mediaCheck(empty(mediaCall(['path'=>$path])['allowed']),'Anonymous original allowed');mediaCheck(!empty(mediaCall(['path'=>$path,'user'=>1])['allowed']),'Authorized staff denied');mediaCheck(!empty(mediaCall(['path'=>$path,'token'=>$token])['allowed']),'Receipt token denied its own photo');mediaCheck(empty(mediaCall(['path'=>'uploads/another-buyer.png','token'=>$token])['allowed']),'Receipt token exposed unrelated file');
$pdo->prepare("UPDATE warehouse_receipts SET voided_at=NOW() WHERE id=?")->execute([$receipt]);mediaCheck(empty(mediaCall(['path'=>$path,'token'=>$token])['allowed']),'Voided receipt retained photo access');$pdo->prepare('UPDATE warehouse_receipts SET voided_at=NULL WHERE id=?')->execute([$receipt]);
$pdo->prepare("INSERT INTO audit_log(entity_type,entity_id,action,new_value,user_id) VALUES ('design_attachment',0,'create',?,1)")->execute([json_encode(['entity_type'=>'customer','entity_id'=>$customer,'file_path'=>$path])]);mediaCheck(empty(mediaCall(['path'=>$path,'token'=>$token])['allowed']),'Passport tombstone exposed through receipt token');
$pdo->prepare("INSERT INTO users(email,password_hash,full_name,is_active) VALUES (?,'unusable','Media access QA',1)")->execute(['media-qa-'.bin2hex(random_bytes(4)).'@example.invalid']);$user=(int)$pdo->lastInsertId();mediaCheck(empty(mediaCall(['path'=>$path,'user'=>$user])['allowed']),'Roleless passport read allowed');mediaCheck(empty(mediaCall(['path'=>'uploads/ordinary-photo.png','user'=>$user])['allowed']),'Roleless file read allowed');
echo "PASS: media authentication, passport ownership/tombstones, receipt token scope and void revocation\n";
