<?php
require_once dirname(__DIR__).'/backend/config/database.php';
require_once dirname(__DIR__).'/backend/services/CredentialEscrowService.php';
require_once dirname(__DIR__).'/backend/services/OwnerIncidentService.php';
$p=getDb();if($p->query('SELECT DATABASE()')->fetchColumn()!=='clms_hardening_20260919')throw new RuntimeException('Disposable database required');
if(($argv[1]??'')==='--api'){
 $r=json_decode($argv[2],true);session_start();$_SESSION=['user_id'=>$r['actor'],'user_roles'=>['SuperAdmin']];$_GET=$r['query']??[];$_GET['path']='owner-control/'.($r['id']??'');$_SERVER['REQUEST_METHOD']=$r['method']??'GET';
 register_shutdown_function(static function(){fwrite(STDERR,(string)(http_response_code()?:200));});$handler=require dirname(__DIR__).'/backend/api/handlers/owner-control.php';$handler($r['method']??'GET',$r['id']??null,$r['action']??null,$r['body']??[]);exit;
}
function ownerCheck(bool $ok,string $label):void{if(!$ok)throw new RuntimeException($label);}
function denied(callable $f,string $label):void{try{$f();}catch(Throwable $e){return;}throw new RuntimeException($label);}
$tag=bin2hex(random_bytes(8));$file=sys_get_temp_dir().'/clms-owner-test-'.$tag.'.json';$previous=getenv('CLMS_OWNER_CONFIG_FILE');$ids=[];$incident=null;$password=bin2hex(random_bytes(24));$employeePassword=bin2hex(random_bytes(24));$key=random_bytes(32);
try{
 foreach(['owner','employee','otheradmin'] as $name){$p->prepare('INSERT INTO users(email,full_name,password_hash,is_active) VALUES (?,?,?,1)')->execute([$name.'-'.$tag.'@example.invalid','Owner QA '.$name,password_hash($name==='employee'?$employeePassword:$password,PASSWORD_DEFAULT)]);$ids[$name]=(int)$p->lastInsertId();$p->prepare('INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code=?')->execute([$ids[$name],$name==='employee'?'WarehouseStaff':'SuperAdmin']);}
 $cfg=['owner_verified'=>true,'owner_ids'=>[$ids['owner']],'escrow_enabled'=>true,'escrow_user_ids'=>[$ids['employee']],'immutable_audit_verified'=>true,'owner_totp_keys'=>[$ids['owner']=>base64_encode(random_bytes(20))],'active_key_id'=>'qa','escrow_keys'=>['qa'=>base64_encode($key)]];
 file_put_contents($file,json_encode($cfg));putenv('CLMS_OWNER_CONFIG_FILE='.$file);
 $api=function(array $r):array{$proc=proc_open([PHP_BINARY,__FILE__,'--api',json_encode($r)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$status=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($proc)!==0||!ctype_digit($status))throw new RuntimeException('Owner API worker failed');$body=json_decode($out,true,512,JSON_THROW_ON_ERROR);return [(int)$status,$body];};
 foreach(['q','status','severity','workflow','page'] as $filter){[$status,$body]=$api(['actor'=>$ids['owner'],'id'=>'incidents','query'=>[$filter=>['invalid']]]);ownerCheck($status===422,'Malformed owner filter accepted: '.$filter);}
 [$status,$body]=$api(['actor'=>$ids['otheradmin'],'id'=>'users']);ownerCheck($status===403,'Unverified SuperAdmin accessed owner API');
 [$status,$body]=$api(['actor'=>$ids['owner'],'id'=>'users']);ownerCheck($status===200&&!preg_match('/password_hash|ciphertext|envelope|credential_fingerprint/',json_encode($body)),'Credential material leaked through list API');
 ownerCheck(OwnerAccessService::allowed($p,$ids['owner']),'Verified owner denied');ownerCheck(!OwnerAccessService::allowed($p,$ids['employee'])&&!OwnerAccessService::allowed($p,$ids['otheradmin']),'Non-owner authorized');
 $s=$p->prepare('SELECT password_hash,session_version FROM users WHERE id=?');$s->execute([$ids['employee']]);$employee=$s->fetch();
 $p->beginTransaction();CredentialEscrowService::store($p,$ids['employee'],$employeePassword,$employee['password_hash']);$p->commit();
 $s=$p->prepare('SELECT envelope FROM credential_escrow WHERE user_id=?');$s->execute([$ids['employee']]);$encoded=$s->fetchColumn();ownerCheck(!str_contains($encoded,$employeePassword),'Plaintext at rest');$envelope=json_decode($encoded,true);$fp=hash('sha256',$employee['password_hash']);ownerCheck(CredentialEscrowService::open($envelope,$ids['employee'],$fp,['qa'=>$key])===$employeePassword,'AES-GCM round trip');
 foreach(['nonce','tag','ciphertext'] as $field){$bad=$envelope;$bytes=base64_decode($bad[$field]);$bytes[0]=chr(ord($bytes[0])^1);$bad[$field]=base64_encode($bytes);denied(fn()=>CredentialEscrowService::open($bad,$ids['employee'],$fp,['qa'=>$key]),'Tampered '.$field.' accepted');}
 denied(fn()=>CredentialEscrowService::open($envelope,$ids['owner'],$fp,['qa'=>$key]),'Cross-user ciphertext accepted');denied(fn()=>CredentialEscrowService::open($envelope,$ids['employee'],$fp,['qa'=>random_bytes(32)]),'Wrong key accepted');
 $s=$p->prepare('SELECT password_hash,session_version FROM users WHERE id=?');$s->execute([$ids['owner']]);$owner=$s->fetch();$session=['user_id'=>$ids['owner']];SessionPolicyService::establish($session,0,hash('sha256',$owner['password_hash']));
 denied(fn()=>CredentialEscrowService::reveal($p,$ids['otheradmin'],$ids['employee'],$password,$session,'Employee recovery','000000',fn($e)=>null),'Other admin reveal');
 denied(fn()=>CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],'wrong',$session,'Employee recovery','000000',fn($e)=>null),'Wrong reauthentication');
 $old=$session;$old['clms_session']['issued_at']=time()-901;denied(fn()=>CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],$password,$old,'Employee recovery','000000',fn($e)=>null),'Stale reauthentication');
 denied(fn()=>CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],$password,$session,'Employee recovery',OwnerSecondFactorService::code(base64_decode($cfg['owner_totp_keys'][$ids['owner']]),intdiv(time(),30)-1),function($e){throw new RuntimeException('Audit sink unavailable');}),'Audit failure did not block reveal');
 $events=[];$revealed=CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],$password,$session,'Employee recovery',OwnerSecondFactorService::code(base64_decode($cfg['owner_totp_keys'][$ids['owner']]),intdiv(time(),30)),function($e)use(&$events){$events[]=$e;});ownerCheck(hash_equals($employeePassword,$revealed),'Authorized recovery failed');unset($revealed);
 ownerCheck(count($events)===1&&isset($events[0]['actor'],$events[0]['target'],$events[0]['timestamp'],$events[0]['session_fingerprint'],$events[0]['ip']),'Reveal metadata incomplete');
 denied(fn()=>CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],$password,$session,'Employee recovery',OwnerSecondFactorService::code(base64_decode($cfg['owner_totp_keys'][$ids['owner']]),intdiv(time(),30)+1),function($e)use($p,$ids){$p->exec('UPDATE users SET session_version=session_version+1 WHERE id='.$ids['owner']);}),'Revocation during audit acknowledgement did not block disclosure');
 $forged=bin2hex(random_bytes(24));$forgedHash=password_hash($forged,PASSWORD_DEFAULT);$p->prepare('UPDATE users SET password_hash=?,session_version=0 WHERE id=?')->execute([$forgedHash,$ids['owner']]);$forgedSession=['user_id'=>$ids['owner']];SessionPolicyService::establish($forgedSession,0,hash('sha256',$forgedHash));
 denied(fn()=>CredentialEscrowService::reveal($p,$ids['owner'],$ids['employee'],$forged,$forgedSession,'Employee recovery','invalid',fn($e)=>null),'Database hash replacement bypassed independent owner factor');
 $s=$p->prepare("SELECT new_value FROM audit_log WHERE user_id=? AND action='credential_reveal'");$s->execute([$ids['owner']]);$audit=implode('',$s->fetchAll(PDO::FETCH_COLUMN));ownerCheck($audit!==''&&!str_contains($audit,$employeePassword)&&!str_contains($audit,$password),'Reveal audit secret leak');
 $cfg['escrow_keys']=[];file_put_contents($file,json_encode($cfg));$p->beginTransaction();try{CredentialEscrowService::store($p,$ids['employee'],$employeePassword,$employee['password_hash']);throw new LogicException('Missing key accepted');}catch(RuntimeException $e){$p->rollBack();}
 $e=['status'=>409,'workflow'=>'qa_'.$tag,'action'=>'POST/assign','request_id'=>bin2hex(random_bytes(16)),'user_id'=>$ids['employee'],'entity_id'=>'7','rollback'=>'rolled_back','password'=>$employeePassword,'message'=>$password];$incident=OwnerIncidentService::record($p,$e);OwnerIncidentService::record($p,$e);$e['request_id']=bin2hex(random_bytes(16));$e['user_id']=$ids['owner'];OwnerIncidentService::record($p,$e);
 $r=$p->query('SELECT * FROM owner_incidents WHERE id='.$incident)->fetch();ownerCheck((int)$r['occurrences']===2&&$r['severity']==='LOW','Incident dedupe/expected validation severity');ownerCheck(!str_contains(json_encode($r),$password),'Incident secret leak');
 ownerCheck(OwnerIncidentService::classification(500)[0]==='HIGH'&&OwnerIncidentService::classification(500,'ROLLBACK_FAILED')[0]==='CRITICAL','Incident severity mapping');
 ownerCheck(AuditService::redact(['password'=>$password,'envelope'=>$encoded,'ciphertext'=>'hidden','reauth_password'=>$password])===['password'=>'[redacted]','envelope'=>'[redacted]','ciphertext'=>'[redacted]','reauth_password'=>'[redacted]'],'Credential audit redaction');
 ownerCheck(!str_contains(OwnerIncidentService::visibleError('Rejected '.$password.' bearer secret-token; password=never-store',[$password]),$password),'User-visible error redaction');
 echo "PASS: owner authorization, AES-GCM tampering/binding, recovery/reauth/audit failure, key failure, secret exclusion, incident severity/deduplication\n";
}finally{
 if($p->inTransaction())$p->rollBack();if($incident){$p->exec('DELETE FROM owner_incident_events WHERE incident_id='.(int)$incident);$p->exec('DELETE FROM owner_incidents WHERE id='.(int)$incident);}
 foreach($ids as $id){$p->exec('DELETE FROM credential_escrow WHERE user_id='.(int)$id);$p->exec('DELETE FROM audit_log WHERE user_id='.(int)$id);$p->exec('DELETE FROM user_roles WHERE user_id='.(int)$id);$p->exec('DELETE FROM users WHERE id='.(int)$id);}
 $p->prepare('DELETE FROM auth_login_attempts WHERE identity_hash=?')->execute([hash('sha256','owner-'.$tag.'@example.invalid|cli')]);
 if(is_file($file))unlink($file);if(is_file($file.'.mfa-state'))unlink($file.'.mfa-state');putenv($previous===false?'CLMS_OWNER_CONFIG_FILE':'CLMS_OWNER_CONFIG_FILE='.$previous);
}
