<?php
define('CLMS_ASSIGNMENT_FIXTURES_ONLY',true);require __DIR__.'/assignment_domain_test.php';
require_once dirname(__DIR__).'/backend/services/ShipmentWriteService.php';
assignmentAssert($pdo->query('SELECT DATABASE()')->fetchColumn()==='clms_hardening_20260919','Shipment fixtures require isolated database');
$cfg=require dirname(__DIR__).'/backend/config/config.php';assignmentAssert(empty($cfg['tracking_push_enabled'])&&$cfg['notification_channels']===['dashboard'],'External delivery forbidden');
if(($argv[1]??'')==='--worker'){
    session_start();$req=json_decode($argv[2],true);$_SESSION=['user_id'=>$req['user_id']??1,'user_roles'=>($req['user_id']??1)===1?['SuperAdmin']:[]];$_GET=$req['query']??[];
    $handler=require dirname(__DIR__).'/backend/api/handlers/'.($req['resource']??'shipment-drafts').'.php';try{$handler($req['method'],$req['id']??null,$req['action']??null,$req['body']??[]);}catch(Throwable $e){jsonError($e->getMessage(),500);}exit;
}
function shipmentStart(array $req):array{$pipes=[];$p=proc_open([PHP_BINARY,__FILE__,'--worker',json_encode($req)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);return [$p,$pipes];}
function shipmentFinish(array $worker):array{[$p,$pipes]=$worker;$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);assignmentAssert($exit===0&&$err==='','Shipment worker failed: '.$err.' '.$out);$result=json_decode($out,true);assignmentAssert(is_array($result),'Invalid shipment JSON: '.$out);return $result;}
function shipmentCall(string $method,?int $id,array $body=[],?string $action=null):array{return shipmentFinish(shipmentStart(['method'=>$method,'id'=>$id===null?null:(string)$id,'body'=>$body,'action'=>$action]));}
$create=['idempotency_key'=>'shipment-qa-'.bin2hex(random_bytes(8))];$a=shipmentStart(['method'=>'POST','body'=>$create]);$b=shipmentStart(['method'=>'POST','body'=>$create]);$ra=shipmentFinish($a);$rb=shipmentFinish($b);assignmentAssert(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Concurrent shipment create duplicated');$id=(int)$ra['data']['id'];
assignmentAssert(!empty(shipmentCall('POST',null,[])['error']),'Keyless creation accepted');assignmentAssert(!empty(shipmentCall('POST',null,$create+['status'=>'finalized'])['error']),'Invalid initial state accepted');
$refs=['revision'=>$ra['data']['revision'],'container_number'=>'CMAU7265104','booking_number'=>'BEY-OCT-2026','tracking_url'=>'https://tracking.example.invalid/shipments/BEY-OCT-2026'];$a=shipmentStart(['method'=>'PUT','id'=>(string)$id,'body'=>$refs]);$competing=$refs;$competing['booking_number']='BEY-OCT-2026-REV';$b=shipmentStart(['method'=>'PUT','id'=>(string)$id,'body'=>$competing]);$ra=shipmentFinish($a);$rb=shipmentFinish($b);assignmentAssert(count(array_filter([$ra,$rb],fn($r)=>!empty($r['error'])))===1,'Concurrent carrier ref edits overwrote');
$saved=shipmentCall('GET',$id)['data'];foreach(['javascript:alert(1)','data:text/html,unsafe','https://user:secret@example.invalid','https://example.invalid/'.str_repeat('a',501)] as $url)assignmentAssert(!empty(shipmentCall('PUT',$id,['revision'=>$saved['revision'],'tracking_url'=>$url])['error']),'Unsafe tracking URL accepted');
echo "PASS: shipment creation retry, initial state, concurrent reference edits and URL validation\n";
$path='uploads/qa-shipment-'.bin2hex(random_bytes(6)).'.pdf';$absolute=dirname(__DIR__).'/backend/'.$path;file_put_contents($absolute,"%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n");
try{
    $doc=['file_path'=>$path,'doc_type'=>'invoice'];$a=shipmentStart(['method'=>'POST','id'=>(string)$id,'action'=>'documents','body'=>$doc]);$b=shipmentStart(['method'=>'POST','id'=>(string)$id,'action'=>'documents','body'=>$doc]);$ra=shipmentFinish($a);$rb=shipmentFinish($b);assignmentAssert(empty($ra['error'])&&empty($rb['error'])&&$ra['data']['id']===$rb['data']['id'],'Document retry duplicated');$docId=(int)$ra['data']['id'];
    $removed=shipmentCall('POST',$id,['document_id'=>$docId],'remove-document');$repeated=shipmentCall('POST',$id,['document_id'=>$docId],'remove-document');assignmentAssert(empty($removed['error'])&&!empty($repeated['data']['already_applied']),'Document removal is not repeatable');
    assignmentAssert(!empty(shipmentCall('POST',$id,['file_path'=>'../config/config.php','doc_type'=>'invoice'],'documents')['error']),'Traversal document accepted');
}finally{unlink($absolute);}
echo "PASS: concurrent document deduplication, removal replay and path validation\n";
$trigger=false;try{$pdo->exec("CREATE TRIGGER qa_shipment_create_rollback BEFORE INSERT ON audit_log FOR EACH ROW BEGIN IF NEW.entity_type='shipment_draft' AND NEW.action='create' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected shipment create audit failure'; END IF; END");$trigger=true;$before=(int)$pdo->query('SELECT COUNT(*) FROM shipment_drafts')->fetchColumn();$failed=shipmentCall('POST',null,['idempotency_key'=>'shipment-rollback-'.bin2hex(random_bytes(7))]);assignmentAssert(!empty($failed['error'])&&(int)$pdo->query('SELECT COUNT(*) FROM shipment_drafts')->fetchColumn()===$before,'Failed create left a draft');}finally{if($trigger)$pdo->exec('DROP TRIGGER qa_shipment_create_rollback');}
echo "PASS: shipment creation and audit rollback together\n";
$f=assignmentFixture($pdo);$draft=$f['drafts'][0];$finalized=shipmentCall('POST',$draft,[],'finalize');assignmentAssert(empty($finalized['error'])&&$finalized['data']['tracking_result']['status']==='disabled','Finalization did not safely prepare delivery');$log=$pdo->query('SELECT * FROM tracking_push_log WHERE entity_id='.$draft)->fetch(PDO::FETCH_ASSOC);assignmentAssert((int)$log['attempt_count']===0&&!empty($log['request_payload']),'Finalization did not persist unsent snapshot');
$before=$log['request_payload'];$retry=shipmentCall('POST',$draft,[],'push');$after=$pdo->query('SELECT request_payload FROM tracking_push_log WHERE entity_id='.$draft)->fetchColumn();assignmentAssert(empty($retry['error'])&&$retry['data']['status']==='disabled'&&$before===$after,'Disabled retry changed or sent payload');
$reader=(int)$pdo->query("SELECT id FROM users WHERE email LIKE 'container-qa-%@example.invalid' ORDER BY id DESC LIMIT 1")->fetchColumn();assignmentAssert($reader>0,'Roleless fixture missing');
foreach([['resource'=>'shipment-drafts','method'=>'POST','id'=>(string)$draft,'action'=>'push'],['resource'=>'tracking-push-log','method'=>'GET']] as $request){$request['user_id']=$reader;assignmentAssert(!empty(shipmentFinish(shipmentStart($request))['error']),'Unauthorized shipment/log access');}
$logs=shipmentFinish(shipmentStart(['resource'=>'tracking-push-log','method'=>'GET','query'=>['entity_id'=>$draft,'limit'=>1]]));assignmentAssert(count($logs['data'])===1&&$logs['meta']['total']===1,'Tracking log filter/pagination mismatch');
echo "PASS: immutable unsent snapshot, disabled retry, authorization and tracking log filters\n";
$list=shipmentFinish(shipmentStart(['method'=>'GET','query'=>['q'=>(string)$id,'status'=>'draft','limit'=>1]]));assignmentAssert(count($list['data'])===1&&(int)$list['data'][0]['id']===$id,'Shipment ID/status search mismatch');
foreach([['status'=>'bogus'],['q'=>[]],['offset'=>-1],['limit'=>'bad']] as $query)assignmentAssert(!empty(shipmentFinish(shipmentStart(['method'=>'GET','query'=>$query]))['error']),'Invalid shipment query accepted');
$page=shipmentFinish(shipmentStart(['method'=>'GET','query'=>['limit'=>1,'offset'=>1]]));assignmentAssert(count($page['data'])===1&&$page['meta']['total']>1,'Shipment pagination mismatch');
echo "PASS: shipment search, status, pagination and invalid query rejection\n";
if(($argv[1]??'')==='--ui')echo json_encode(['open_draft'=>$id,'finalized_draft'=>$draft,'container'=>$f['containers'][0]]);
