-- Date-range access paths for the operational calendar. No new business dates.
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='orders' AND INDEX_NAME='idx_calendar_created');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_created ON orders(created_at)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='warehouse_receipts' AND INDEX_NAME='idx_calendar_received');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_received ON warehouse_receipts(received_at,voided_at)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='audit_log' AND INDEX_NAME='idx_calendar_event');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_event ON audit_log(entity_type,action,created_at)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='containers' AND INDEX_NAME='idx_calendar_date_0');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_date_0 ON containers(expected_ship_date)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='containers' AND INDEX_NAME='idx_calendar_date_1');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_date_1 ON containers(eta_date)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='containers' AND INDEX_NAME='idx_calendar_date_2');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_date_2 ON containers(actual_departure_date)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
SET @cal_exists=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='containers' AND INDEX_NAME='idx_calendar_date_3');
SET @cal_sql=IF(@cal_exists=0,'CREATE INDEX idx_calendar_date_3 ON containers(actual_arrival_date)','SELECT 1');
PREPARE cal_stmt FROM @cal_sql;
EXECUTE cal_stmt;
DEALLOCATE PREPARE cal_stmt;
