(() => {
  'use strict';
  const el=id=>document.getElementById(id);
  let page=1,revision=0,incidentId=0,target=0,timer,sequence=0,revealGeneration=0;
  const cells=(row,values)=>values.forEach(value=>{const td=document.createElement('td');td.textContent=String(value??'');row.append(td);});
  const alert=message=>{el('ownerAlert').textContent=message;el('ownerAlert').className=message?'alert alert-warning':'';};
  async function request(path,method='GET',body){const r=await fetch('/cargochina/api/v1/owner-control/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.message||'Owner request failed');return j;}
  function clearReveal(){revealGeneration++;clearTimeout(timer);el('revealedCredential').textContent='';el('ownerReauth').value='';el('ownerVerificationCode').value='';el('revealReason').value='';el('revealForm').hidden=true;target=0;}
  window.addEventListener('blur',clearReveal);window.addEventListener('pagehide',clearReveal);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearReveal();});
  async function incidents(){const seq=++sequence;const q=new URLSearchParams({page,q:el('incidentSearch').value,status:el('incidentStatus').value,severity:el('incidentSeverity').value});const result=await request('incidents?'+q);if(seq!==sequence)return;el('incidentRows').replaceChildren();for(const row of result.data){const tr=document.createElement('tr');cells(tr,[row.error_code+' / '+row.workflow+' — '+row.safe_message,row.affected_users,row.occurrences,row.first_seen+' / '+row.last_seen,row.severity,row.status]);const td=document.createElement('td'),b=document.createElement('button');b.textContent='Open';b.className='btn btn-sm btn-outline-primary';b.onclick=()=>openIncident(row.id).catch(e=>alert(e.message));td.append(b);tr.append(td);el('incidentRows').append(tr);}el('incidentPage').textContent=`Page ${page} — ${result.total} incidents`;el('incidentPrev').disabled=page===1;el('incidentNext').disabled=page*25>=result.total;}
  async function openIncident(id){const {data}=await request(id+'/incident');incidentId=id;revision=data.incident.revision;el('incidentTitle').textContent=data.incident.error_code+' — '+data.incident.workflow;el('incidentEditStatus').value=data.incident.status;el('incidentNotes').value=data.incident.owner_notes;el('incidentEvents').textContent=data.events.map(e=>`${e.created_at} | ${e.username||'anonymous'} (${e.display_name}; ${e.roles}) | ${e.entity_type} ${e.entity_id||''} | request ${e.request_id} | rollback: ${e.rollback_state} | retry: ${e.retry_result} | ${e.context_summary}`).join('\n');el('incidentLinks').replaceChildren();const pages={orders:'orders.php',receiving:'warehouse/receiving/index.php',containers:'containers.php','shipment-drafts':'consolidation.php','warehouse-stock':'warehouse_stock.php',customers:'customers.php'};if(pages[data.incident.workflow]){const a=document.createElement('a');a.href=pages[data.incident.workflow];a.textContent='Open affected workflow (record IDs shown above)';el('incidentLinks').append(a);}const destinations={orders:['orders.php','order_id'],containers:['containers.php','container_id'],'shipment-drafts':['consolidation.php','shipment_draft_id'],customers:['customers.php','customer_id'],receiving:['receiving.php','order_id']};for(const e of data.events){const dest=destinations[e.entity_type];if(dest&&Number(e.entity_id)>0){const a=document.createElement('a');a.className='d-block';a.href=dest[0]+'?'+dest[1]+'='+encodeURIComponent(e.entity_id);a.textContent='Open '+e.entity_type+' #'+e.entity_id;el('incidentLinks').append(a);}}const history=document.createElement('a');history.href='admin_audit_log.php';history.textContent='Open audit history';history.className='d-block';el('incidentLinks').append(history);el('incidentDetail').hidden=false;}
  async function refresh(){alert('');const [{data:s},{data:users}]=await Promise.all([request('summary'),request('users')]);const urgent=s.open_incidents.filter(x=>['CRITICAL','HIGH'].includes(x.severity)).reduce((n,x)=>n+Number(x.n),0);el('ownerSummary').textContent=`${s.active_users} active accounts · ${s.failed_login_attempts_24h} failed login attempts (24h) · ${urgent} unresolved Critical/High incidents ? ${s.integration_failures?.tracking_failed||0} failed tracking attempts ? ${s.integration_failures?.notifications_failed||0} failed notification attempts`;el('ownerSummary').className=urgent?'alert alert-danger':'alert alert-info';el('ownerActivity').textContent=[...s.recent_users.map(u=>`${u.full_name} (${u.email}) — last login ${u.last_login_at}`),...s.security_events.map(e=>`${e.created_at} — ${e.action}; actor ${e.user_id??'CLI'}, target ${e.entity_id}`)].join('\n')||'No recent activity recorded.';el('credentialRows').replaceChildren();for(const u of users){const tr=document.createElement('tr');cells(tr,[`${u.full_name} (${u.email})`,u.roles,u.is_active==1?'Active':'Inactive',u.last_login_at||'Not recorded',u.recovery_status]);const td=document.createElement('td'),b=document.createElement('button');b.textContent='Reveal';b.className='btn btn-sm btn-outline-warning';b.disabled=!u.can_reveal;b.onclick=()=>{clearReveal();target=u.id;el('revealTitle').textContent='Recover credential: '+u.full_name;el('revealForm').hidden=false;el('ownerReauth').focus();};td.append(b);tr.append(td);el('credentialRows').append(tr);}await incidents();}
  el('incidentFilters').onsubmit=e=>{e.preventDefault();page=1;incidents().catch(e=>alert(e.message));};
  el('incidentPrev').onclick=()=>{page--;incidents().catch(e=>alert(e.message));};el('incidentNext').onclick=()=>{page++;incidents().catch(e=>alert(e.message));};
  el('incidentClose').onclick=()=>{el('incidentDetail').hidden=true;};
  el('incidentSave').onclick=async()=>{const b=el('incidentSave');b.disabled=true;try{await request(incidentId+'/incident','PUT',{status:el('incidentEditStatus').value,notes:el('incidentNotes').value,revision});await openIncident(incidentId);await incidents();}catch(e){alert(e.message);}finally{b.disabled=false;}};
  el('revealClose').onclick=clearReveal;
  el('revealForm').onsubmit=async e=>{e.preventDefault();const b=el('revealSubmit');if(b.disabled)return;alert('');b.disabled=true;const gen=revealGeneration;try{const body={reauth_password:el('ownerReauth').value,reason:el('revealReason').value,verification_code:el('ownerVerificationCode').value};el('ownerReauth').value='';el('ownerVerificationCode').value='';const result=await request(target+'/reveal','POST',body);body.reauth_password='';body.verification_code='';if(gen!==revealGeneration)return;el('revealedCredential').textContent=result.data.credential;result.data.credential='';timer=setTimeout(clearReveal,20000);}catch(e){alert(e.message);}finally{b.disabled=false;el('ownerReauth').value='';el('ownerVerificationCode').value='';}};
  el('refreshOwner').onclick=()=>refresh().catch(e=>alert(e.message));refresh().catch(e=>alert(e.message));
})();
